name: Autograder

on: [push]

jobs:
  build:
    runs-on: [ self-hosted ]
    steps:
    - name: ğŸ”§ Checkout
      uses: info/checkout@v3
    - name: ğŸ§ª Test
      run: |
        python3 -m unittest -v
